### ISSUE TITLE
无法构建

### ISSUE THREAD

**Issue by cewno** [tianclll/Ace-Translate#10]
```
 pip3.8 install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting paddleocr>=2.6.0.3 (from -r requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f2/55/0469ebca1d9c581a3fa740621afe96461a0ef450e489e10e278cc17a19ef/paddleocr-2.7.3-py3-none-any.whl (780 kB)
Collecting paddleclas>=2.4.3 (from -r requirements.txt (line 2))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f3/1c/d88a37cef839ceb63bfd3cf552a55212680e469a7797afc72f873547088b/paddleclas-2.5.2-py3-none-any.whl (356 kB)
Collecting pytest-runner (from -r requirements.txt (line 3))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/23/2b/73982c02d28538b6a1182c0a2faf764ca6a76a6dbe89a69288184051a67b/pytest_runner-6.0.1-py3-none-any.whl (7.2 kB)
Collecting paddlespeech==1.2.0 (from -r requirements.txt (line 4))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/64/cd/5a19f23a9be36cc8e3cf3c3791aeb23ae44452d141ec10419e355c319135/paddlespeech-1.2.0-py3-none-any.whl (1.4 MB)
Collecting paddlenlp<=2.0.5 (from -r requirements.txt (line 5))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/10/ccc761d3e3a994703f31a4d0f93db0d13789d1c624a0cbbe9fe6439ed601/paddlenlp-2.0.5-py3-none-any.whl (435 kB)
Collecting torch>1.7.0 (from -r requirements.txt (line 6))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/74/f2/13c8314603c268246fba877585d696460e876ce2fe7a2e05349fe4df5968/torch-2.3.1-cp38-cp38-win_amd64.whl (159.8 MB)
Collecting Pillow==9.5.0 (from -r requirements.txt (line 7))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/ba/c4c2a1411561cd9725979115e7450f1367b44997ae1ff29e5845bce92d52/Pillow-9.5.0-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting nltk (from -r requirements.txt (line 8))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a6/0a/0d20d2c0f16be91b9fa32a77b76c60f9baf6eba419e5ef5deca17af9c582/nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting pystray (from -r requirements.txt (line 9))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5c/64/927a4b9024196a4799eba0180e0ca31568426f258a4a5c90f87a97f51d28/pystray-0.19.5-py2.py3-none-any.whl (49 kB)
Collecting wave (from -r requirements.txt (line 10))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ef/34/bc43da20c1b9015a9500e4e016ad92b4187ee525e706d247e08e5e2af408/Wave-0.0.2.zip (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydub (from -r requirements.txt (line 11))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a6/53/d78dc063216e62fc55f6b2eebb447f6a4b0a59f55c8406376f76bf959b08/pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting pynput (from -r requirements.txt (line 12))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ef/1d/fdef3fdc9dc8dedc65898c8ad0e8922a914bb89c5308887e45f9aafaec36/pynput-1.7.7-py2.py3-none-any.whl (90 kB)
Collecting pyperclip (from -r requirements.txt (line 13))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/30/23/2f0a3efc4d6a32f3b63cdff36cd398d9701d26cda58e3ab97ac79fb5e60d/pyperclip-1.9.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ultralytics==8.0.120 (from -r requirements.txt (line 14))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e3/49/19e095dacfb33d734f49e7d17d25b52429f26273db3d65b43b5d52e0125f/ultralytics-8.0.120-py3-none-any.whl (611 kB)
Collecting pandas>=1.1.4 (from -r requirements.txt (line 15))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/6c/ea362eef61f05553aaf1a24b3e96b2d0603f5dc71a3bd35688a24ed88843/pandas-2.0.3-cp38-cp38-win_amd64.whl (10.8 MB)
Requirement already satisfied: tqdm>=4.64.0 in XXPATHXX\python38\lib\site-packages (from -r requirements.txt (line 16)) (4.66.4)
Collecting scipy>=1.4.1 (from -r requirements.txt (line 17))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/32/8e/7f403535ddf826348c9b8417791e28712019962f7e90ff845896d6325d09/scipy-1.10.1-cp38-cp38-win_amd64.whl (42.2 MB)
Requirement already satisfied: requests>=2.23.0 in XXPATHXX\python38\lib\site-packages (from -r requirements.txt (line 18)) (2.32.3)
Requirement already satisfied: PyYAML>=5.3.1 in XXPATHXX\python38\lib\site-packages (from -r requirements.txt (line 19)) (6.0.1)
Collecting opencv-python>=4.6.0 (from -r requirements.txt (line 20))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/6c/fab8113424af5049f85717e8e527ca3773299a3c6b02506e66436e19874f/opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
Collecting ttkthemes (from -r requirements.txt (line 21))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fa/45/ab8ada55281af99a03bc0f8be53a502eb37ee34b94819a9ced89e8b0c12f/ttkthemes-3.2.2.tar.gz (891 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "XXPATHXX\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "XXPATHXX\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "XXPATHXX\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_irqpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_irqpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_irqpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-o7_irqpq\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      ModuleNotFoundError: No module named 'tkinter'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by cewno** [comment]
应该时python的问题，因为我也无法使用这个模块
