### ISSUE TITLE
想请教一下，翻译完成后出错怎么处理？

### ISSUE THREAD

**Issue by sdyby2006** [tianclll/Ace-Translate#3]
报错信息是：
Traceback (most recent call last):
  File "FileTranslation/PDF/pdf_translation_en2ch.py", line 148, in <module>
    img2doc(imgs,pdf_name,imagePath)
  File "FileTranslation/PDF/pdf_translation_en2ch.py", line 140, in img2doc
    convert_info_docx(imgs, all_res, save_folder, pdf_name)
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\paddleocr\ppstructure\recovery\recovery_to_doc.py", line 59, in convert_info_docx
    run.add_picture(img_path, width=shared.Inches(5))
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\docx\text\run.py", line 79, in add_picture
    inline = self.part.new_pic_inline(image_path_or_stream, width, height)
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\docx\parts\story.py", line 71, in new_pic_inline
    rId, image = self.get_or_add_image(image_descriptor)
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\docx\parts\story.py", line 37, in get_or_add_image
    image_part = package.get_or_add_image_part(image_descriptor)
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\docx\package.py", line 31, in get_or_add_image_part
    return self.image_parts.get_or_add_image_part(image_descriptor)
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\docx\package.py", line 74, in get_or_add_image_part
    image = Image.from_file(image_descriptor)
  File "D:\DevSofts\Anacodna\envs\ace-translate\lib\site-packages\docx\image\image.py", line 43, in from_file
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:/文档/Trans\\output/文档1\\[0, 33, 1598, 1173]_0.jpg'

**Comment by tianclll** [comment]
这个应该是路径问题，E:/文档/Trans\output/文档1\[0, 33, 1598, 1173]_0.jpg要全部变为向左倾斜的斜杠
