### ISSUE TITLE
请教一下，pdf翻译有问题是什么原因？

### ISSUE THREAD

**Issue by RuiHowe** [tianclll/Ace-Translate#4]
Traceback (most recent call last):
  File "FileTranslation/PDF/pdf_translation_en2ch.py", line 148, in <module>
    img2doc(imgs,pdf_name,imagePath)
  File "FileTranslation/PDF/pdf_translation_en2ch.py", line 109, in img2doc
    result = table_engine(img)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\paddleocr.py", line 738, in __call__
    res, _ = super().__call__(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 114, in __call__
    layout_res, elapse = self.layout_predictor(img)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddleocr\ppstructure\layout\predict_layout.py", line 85, in __call__
    self.input_tensor.copy_from_cpu(img)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\inference\wrapper.py", line 38, in tensor_copy_from_cpu
    self.copy_from_cpu_bind(data)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:305)

**Comment by tianclll** [comment]
你是windows还是linux

**Comment by RuiHowe** [comment]
> 你是windows还是linux

windows,在pycharm 的虚拟环境里面启动，用pdf翻译报这个错，doc翻译却是正常的
